[[mon_defs]]
id = "fierasaur" # IDs are case-insensitive and unique to each def; for the default version of a mon, they are usually that mon's name
species = "Fierasaur" # species name
types = ["fire"]
abilities = [
    "fire_resistant",
    "tough_eyes"
]
height = 0.35 # meters
weight = 1.5 # kilograms
evolutions = [
    # none for now
]
possible_moves = [
    [1, "headbutt"],
    [1, "growl"],
]
base_exp = 64

[mon_defs.base_stats]
hp = 50
atk = 50
def = 50
spatk = 50
spdef = 50

[mon_defs.gender_ratio]
female = 0.395
male = 0.395
non-binary = 0.1
agender = 0.1
not_listed = 0.01

[[mon_defs]]
id = "aguana"
species = "Aguana"
types = ["water"]
abilities = [
    "cold_resistant"
]
height = 0.3 # meters
weight = 1.2 # kilograms
evolutions = [
    # none for now
]
possible_moves = [
    [1, "scratch"],
    [1, "hiss"],
]
base_exp = 64

[mon_defs.base_stats]
hp = 50
atk = 50
def = 50
spatk = 50
spdef = 50

[mon_defs.gender_ratio]
female = 0.395
male = 0.395
non-binary = 0.1
agender = 0.1
not_listed = 0.01

[[mon_instances]]
id = "fiona"
def = "fierasaur" # the ID of the mon_def
nickname = "Fiona" # individual mon's name
ability = "fire_resistant"
level = 1
current_moves = [
    "headbutt",
    "growl"
]
gender = "female"

[[mon_instances]]
id = "alex"
def = "aguana"
nickname = "Alex"
ability = "cold_resistant"
level = 1
current_moves = [
    "scratch",
    "hiss"
]
gender = "genderfluid"

[type_data.fire]
resistant_to = ["plant"]
weak_to = ["water"]

[type_data.water]
resistant_to = ["fire"]
weak_to = ["plant"]

[type_data.plant]
resistant_to = ["water"]
weak_to = ["fire"]

[type_data.normal]
resistant_to = []
weak_to = []

[[abilities]]
id = "fire_resistant"
name = "Fire Resistant"
description = "This mon can't receive a Burn."

[[abilities]]
id = "tough_eyes"
name = "Tough Eyes"
description = "This mon can't have their accuracy affected by physical blinding moves."

[[abilities]]
id = "cold_resistant"
name = "Cold Resistant"
description = "This mon can't be Frozen."

[[moves]]
id = "headbutt"
name = "Headbutt"
accuracy = 75
base_power = 20
category = "physical"
pp = 40
priority = 0
# one_foe, all_foes, one_ally, all_allies, self, all_allies_and_self, any_mon, 
# any_mon_including_self, all_mons, all_mons_including_self, entire_arena, entire_arena_including_self
target = "one_foe" 
type = "normal"

[[moves]]
id = "scratch"
name = "Scratch"
accuracy = 100
base_power = 15
category = "physical"
pp = 40
priority = 0
target = "one_foe"
type = "normal"

[[moves]]
id = "growl"
name = "Growl"
accuracy = 100
base_power = 0
category = "status"
pp = 30
priority = 1
target = "one_foe"
type = "normal"
[[moves.boosts]]
atk = -1 # -1 stage of attack for target

[[moves]]
id = "hiss"
name = "Hiss"
accuracy = 100
base_power = 0
category = "status"
pp = 30
priority = 1
target = "one_foe"
type = "normal"
[[moves.boosts]]
def = -1

